name: Add job summary as comment to PR

on:
  workflow_run:
    workflows: [Check Licenses]
    types:
      - completed

jobs:
  license:
    uses: netomi/dash-licenses/.github/workflows/addLicenseCheckCommentForForks.yml@master
    permissions:
      pull-requests: write
