name: Add job summary as comment to PR

on:
  workflow_run:
    workflows: [Check Licenses]
    types:
      - completed

jobs:
  add-job-summary-as-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: >
      github.event.workflow_run.event == 'pull_request'

    # github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.workflow_run) }}
        run: echo "$GITHUB_CONTEXT"
      # - name: 'Comment on PR'
      #   uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       var fs = require('fs');

      #       const issue_number = Number(fs.readFileSync('./pr-number.txt'));
      #       const body = fs.readFileSync('./body.txt', { encoding: 'utf8', flag: 'r' });

      #       await github.rest.issues.createComment({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: issue_number,
      #         body: body
      #       });
