name: Check Licenses

on:
  workflow_dispatch:
  pull_request:
    branches:
     - 'main'
  issue_comment:
    types: [created]

jobs:
  license:
    uses: netomi/dash-licenses/.github/workflows/mavenLicenseCheck.yml@master
    permissions:
      contents: write
      issues: write
      pull-requests: write
    with:
      projectId: 'technology.cbi'
    secrets:
      gitlabAPIToken: ${{ secrets.GITLAB_API_TOKEN }}

